word_list = [
    "der", "die", "das", "und", "sein", "in", "ein", "zu", "haben", "ich",
    "werden", "sie", "von", "nicht", "mit", "es", "auf", "für", "er", "so",
    "dass", "können", "dies", "als", "ihr", "ja", "wie", "bei", "oder", "wir",
    "aber", "was", "dann", "da", "man", "doch", "wenn", "nur", "müssen", "sagen",
    "um", "noch", "vor", "nach", "über", "mehr", "kein", "mein", "durch", "schon",
    "ganz", "wo", "weil", "all", "uns", "unter", "denn", "immer", "jede", "dieser",
    "jeder", "etwas", "nichts", "beim", "dort", "heute", "gestern", "morgen", "jetzt", "dazu",
    "darauf", "daher", "deshalb", "damit", "darum", "davon", "daran", "danach", "einfach", "schwer",
    "lang", "kurz", "gut", "schlecht", "neu", "alt", "jung", "schön", "hässlich", "klein",
    "groß", "hoch", "tief", "weit", "nah", "schnell", "langsam", "besser", "schlechter", "wieder",
    "zurück", "immerhin", "fast", "schließlich", "bereits", "erst", "nochmal", "oft", "selten", "manchmal",
    "meistens", "nie", "überall", "nirgendwo", "hier", "drüben", "oben", "unten", "links", "rechts",
    "innen", "außen", "vorne", "hinten", "zwischen", "seit", "seitdem", "obwohl", "ob", "falls",
    "damals", "darüber", "hinaus", "insbesondere", "trotzdem", "sobald", "solange", "während", "jedoch", "sondern",
    "nun", "bereits", "eigentlich", "natürlich", "einmal", "keineswegs", "irgendwo", "nirgendwo", "nirgendwann", "überdies",
    "außerdem", "ferner", "zugleich", "weiterhin", "jedoch", "somit", "folglich", "also", "zudem", "wenigstens",
    "mindestens", "höchstens", "kaum", "ziemlich", "äußerst", "sehr", "recht", "ebenfalls", "sowieso", "dennoch",
    "indessen", "zwar", "freilich", "gleichwohl", "gewiß", "wohl", "scheinbar", "angeblich", "tatsächlich", "wirklich",
    "genau", "ungefähr", "circa", "etwa", "rund", "sofort", "gleich", "plötzlich", "endlich", "erstmals",
    "zunächst", "anschließend", "danach", "bald", "früh", "später", "künftig", "vorher", "bereits", "neulich",
    "kürzlich", "eben", "gerade", "soeben", "derzeit", "momentan", "nunmehr", "jetzt", "damit", "daraufhin",
    "hiermit", "folglich", "weshalb", "woraufhin", "wobei", "worin", "wohin", "woher", "worauf", "woraus",
    "wodurch", "worüber", "womit", "worunter", "worüber", "woran", "wozu", "worum", "weswegen", "weshalb",
    "darum", "daher", "deswegen", "folglich", "somit", "also", "mithin", "dabei", "darüberhinaus", "ansonsten",
    "stattdessen", "hierbei", "indessen", "nebenbei", "übrigens", "überdies", "nochmals", "wiederum", "erneut", "abermals",
    "einzig", "bloß", "lediglich", "allein", "nurmehr", "nichtsdestotrotz", "nichtsdestoweniger", "dennoch", "gleichwohl", "obgleich",
    "obschon", "wenngleich", "wiewohl", "zwar", "freilich", "allerdings", "indes", "indessen", "hingegen", "vielmehr",
    "anders", "anderswo", "ansonsten", "gegebenenfalls", "bestenfalls", "allenfalls", "keinesfalls", "keineswegs", "niemals", "immerzu",
    "fortwährend", "ständig", "permanent", "dauernd", "ewig", "zeitweise", "zwischenzeitlich", "gelegentlich", "öfter", "bisweilen",
    "hin und wieder", "ab und zu", "manchmal", "selten", "vereinzelt", "spärlich", "öfters", "gelegentlich", "meist", "überwiegend",
    "größtenteils", "weitgehend", "zumeist", "allgemein", "insgesamt", "durchaus", "grundsätzlich", "prinzipiell", "überhaupt", "keineswegs",
    "niemals", "auf keinen Fall", "bei weitem", "mitnichten", "zweifellos", "ohne Zweifel", "ohnehin", "sowieso", "selbstverständlich", "natürlich",
    "klar", "offenbar", "offensichtlich", "eindeutig", "zweifelsohne", "ganz sicher", "sicherlich", "fraglos", "gewiss", "bestimmt",
    "wohl", "eventuell", "möglicherweise", "vielleicht", "unter Umständen", "gegebenenfalls", "denkbar", "machbar", "potenziell", "wahrscheinlich",
    "höchstwahrscheinlich", "ziemlich sicher", "fast sicher", "sicher", "unsicher", "unklar", "fraglich", "zweifelhaft", "unsicherlich", "ungewiss",
    "bestenfalls", "schlimmstenfalls", "höchstens", "maximal", "minimal", "wenigstens", "mindestens", "ungefähr", "circa", "etwa",
    "rund", "knapp", "exakt", "präzise", "genau", "grob", "ungefähr", "annähernd", "sozusagen", "gewissermaßen",
    "quasi", "praktisch", "theoretisch", "tatsächlich", "wirklich", "in der Tat", "faktisch", "real", "wahrlich", "buchstäblich",
    "anscheinend", "scheinbar", "augenscheinlich", "angeblich", "vermeintlich", "mutmaßlich", "vermutlich", "wohl", "offenbar", "offensichtlich",
    "klarerweise", "deutlich", "eindeutig", "unmissverständlich", "explizit", "implizit", "konkret", "abstrakt", "allgemein", "besonders",
    "insbesondere", "speziell", "vor allem", "hauptsächlich", "überwiegend", "größtenteils", "weitgehend", "zum Teil", "teilweise", "manchmal",
    "gelegentlich", "bisweilen", "immer wieder", "ständig", "fortlaufend", "permanent", "dauernd", "stetig", "fortwährend", "kontinuierlich"
]
